# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3f5b4ca7ae1cbc4c1526c272a1107c1c8c68a0d05fc49a362b03079e9b208e68f957a84f4e377dd65c2f6b59b680d205280f7d2092dd9dafa15166d7a03801

test:
  secret_key_base: 624b91dacb4d38e2cdd82c57d617e11b1ea8e6d3f0dc91293018059b56079124bf6ff56475810856d1776eb8adf7c53843485fbdee3754f914d1e3fd4e49cd02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
